update cache on every commit

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -9,6 +9,21 @@ env:
       )
     }}
 
+  build_and_cache: |-
+    build_and_cache() {
+      arch="$1"
+      if ! docker buildx build \
+        --platform linux/$arch \
+        --cache-from type=local,src=/home/runner/tmp/$arch \
+        --cache-to type=local,dest=/home/runner/tmp/$arch \
+        --tag ${GITHUB_REPOSITORY,,}:$arch \
+        --file Dockerfile . ;
+      then
+        echo "::error::Docker-Build Error. $arch Cache will be deleted now!"
+        rm -rf /home/runner/tmp/$arch/
+      fi
+    }
+
 jobs:
   build:
     name: Build
@@ -18,12 +33,13 @@ jobs:
     - name: Checkout
       uses: actions/checkout@master
 
-    - name: Cache docker buildx
-      uses: actions/cache@v2
+    - name: update cache on every commit
+      uses: actions/cache@v3
       with:
-        path: |
-          /home/runner/tmp
-        key: docker-tmp
+        path: /home/runner/tmp
+        key: docker-${{ github.run_id }}
+        restore-keys: |
+          docker-
 
     - name: Compute Docker Tag
       if: fromJSON(env.should_push_image)
@@ -50,25 +66,15 @@ jobs:
         docker buildx create --use
         docker buildx inspect --bootstrap
 
-    - name: Fill AMD64 cache
-      if: fromJSON(env.should_push_image)
-      run: |
-        docker buildx build \
-        --platform linux/amd64 \
-        --cache-from type=local,src=/home/runner/tmp/amd64 \
-        --cache-to type=local,dest=/home/runner/tmp/amd64 \
-        --tag ${GITHUB_REPOSITORY,,}:amd64 \
-        --file cicd/Dockerfile .
-    
-    - name: Fill ARM64 cache
-      if: fromJSON(env.should_push_image)
-      run: |
-        docker buildx build \
-        --platform linux/arm64 \
-        --cache-from type=local,src=/home/runner/tmp/arm64 \
-        --cache-to type=local,dest=/home/runner/tmp/arm64 \
-        --tag ${GITHUB_REPOSITORY,,}:arm64 \
-        --file cicd/Dockerfile .
+      - name: Fill AMD64 cache
+        run: |
+          ${{ env.build_and_cache }} 
+          build_and_cache amd64
+
+      - name: Fill ARM64 cache
+        run: |
+          ${{ env.build_and_cache }} 
+          build_and_cache arm64
 
     - name: Docker build from cache and push
       if: fromJSON(env.should_push_image)
